docs_dir: 'docs'
site_dir: 'site'
site_name: Patchbox OS Documentation
site_author: UAB VILNIAUS BLOKAS
google_analytics: ['UA-44135535-1', 'auto']
use_directory_urls: true
theme:
  name: 'material'
  favicon: 'favicon.ico'
  logo: 'images/logo.svg'
  palette:
    primary: 'white'
    accent: 'white'
  custom_dir: 'blokas-docs-theme'
site_url: https://blokas.io/patchbox-os/docs/
extra:
  # discourse: 'https://community.blokas.io/'
  # disqus: 'fake'
  social:
    - type: 'github'
      link: 'https://github.com/BlokasLabs'
    - type: 'twitter'
      link: 'https://twitter.com/blokaslabs'
    - type: 'facebook'
      link: 'https://www.facebook.com/blokaslabs/'
repo_name: 'patchbox-os-gen-wiki'
repo_url: 'https://github.com/BlokasLabs/patchbox-os-gen/'
markdown_extensions:
  - toc:
      permalink: '#'
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
  - footnotes

copyright: '&copy; 2020 VILNIAUS BLOKAS UAB'

nav:
  - Introduction: index.md
  - Raspberry Pi Essentials: 
      - Install the Operating System to the SD Card: install-os-to-sd-card.md
      - Find the IP Address: find-the-ip-address.md
      - Remote Control Options: remote-control.md
  - First Run: 
      - First Run Options: first-run-options.md
      - Setup Wizard: setup-wizard.md
  - Modules: 
      - Modules: modules.md
      - Creating a Module: creating-a-module.md
      - patchbox-module.json reference: patchbox-module-json.md
  - Software Guides: software-guides.md
  - amidiauto: amidiauto.md
  - Troubleshooting: troubleshooting.md

plugins:
  - search
  - redirects:
        redirect_maps:
            'GettingStarted.md': 'first-run-options.md'
            'Module-Internals.md': 'creating-a-module.md'
            'SoftwareGuides.md': 'software-guides.md'

